version: '1.0'
stages:
- build
- test
- push
- shownode
steps:
  BuildDockerImage:
    title: Building Docker Image
    type: build
    stage: 'build'
    image_name: k8snative/tutorialreactdocker
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}'
    dockerfile: Dockerfile
  UnitTest:
    title: Run unit test
    stage: 'test'
    image: ${{BuildDockerImage}}
    working_directory: IMAGE_WORK_DIR
    commands:
      - CI=true npm test
  PushToQuay:
    title: Push to Quay
    type: push
    stage: 'push'
    candidate: ${{BuildDockerImage}}
    tag: '${{CF_SHORT_REVISION}}'
    registry: 'quay'
  ShowNodeTestOnly:
    title: Show available nodes
    image: lachlanevenson/k8s-kubectl
    stage: 'shownode'
    commands:
      - config get-contexts
      - config use-context standard-cluster-1@StackDriver-Env-Test
      - get ns 
      - get pods --all-namespaces
      - get nodes
